apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "azp-agent-job.fullname" . }}-config
data:
  AZP_URL: "{{ .Values.azp.url }}"
  AZP_POOL: "{{ .Values.azp.pool }}"
  AZP_POOLID: "{{ .Values.azp.poolId }}"