{{- if .Values.imagePullSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azp-agent-job.fullname" . }}-pull-secret
  labels:
    {{- include "azp-agent-job.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "azp-agent-job.imagePullSecret" . }}
{{- end }}