apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azp-agent-job.fullname" . }}-token
  labels:
    {{- include "azp-agent-job.labels" . | nindent 4 }}
type: Opaque
stringData:
  AZP_TOKEN: {{ .Values.azp.token }}