{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azp-agent-job.serviceAccountName" . }}
  labels:
    {{- include "azp-agent-job.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.imagePullSecret.use }}
imagePullSecrets:
  - name: {{ include "azp-agent-job.fullname" . }}-pull-secret
{{- end }}
{{- end }}
